name = "USRPHardwareDriver_jll"
uuid = "e339f254-40e1-517e-839f-dc67f1dbd84e"
version = "4.1.0+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
libusb_jll = "a877fdc9-fe69-5ed6-b93d-11ecd0dc2d49"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
boost_jll = "28df3c45-c428-5900-9ff8-a3135698ca75"

[compat]
JLLWrappers = "1.2.0"
julia = "1.6"
libusb_jll = "1.0.24"
boost_jll = "=1.76.0"
